services:
  adminer:
    container_name: mf-adminer
    restart: always
    image: adminer
    ports:
      - 8080:8080
  db:
    container_name: mf-postgres-dev
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: memorize_facts_backend_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
  db-test:
    container_name: mf-postgres-test
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: memorize_facts_backend_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
volumes:
  postgres:
