name: Push or merge to main branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: "Build and test"
    uses: ./.github/workflows/build_and_test.yml

  release-job:
    name: "Autorelease using Semantic Release"
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@4.6.3
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
