name: Push and merge to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  test-job:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: node:14

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: memorize_facts_backend_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dbpassword
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test
