name: Push and merge to master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and test"
    uses: .github/workflows/reusable/build_and_test.yml
